"""add language to posts

Revision ID: 035386a789df
Revises: 7f8878ac0d7f
Create Date: 2020-04-08 16:26:32.346446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035386a789df'
down_revision = '7f8878ac0d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
